---
# handlers file for postfixadmin-role---

- name: Restarted Firewalld
  service:
    name: firewalld
    enabled: true
    state: restarted

- name: Started and Enabled php-fpm
  service:
    name: php-fpm
    enabled: true
    state: started

- name: Restarted nginx
  service:
    name: nginx
    enabled: true
    state: restarted

- name: Restarted php-fpm
  service:
    name: php-fpm
    state: restarted
